fix: Assign correct header to sub sections and articles
SPANDigital/presidium-theme-website pull request #315
Opened 2024-11-08 07:13 UTC by julianbyte

## Description
Updates the article title template to dynamically assign heading levels based on the article's depth in the content hierarchy. The depth calculation logic has been adjusted to skip the global site title ($.Site.Title), which Hugo treats as an implicit top-level parent. By ignoring this site title, the change prevents an extra heading level from being added and ensures that each article’s header level correctly reflects its actual position within the hierarchy.

## Issue
- [PRSDM-6186](https://spandigital.atlassian.net/browse/PRSDM-6186)

## Screenshots
Before:
<img width="1440" alt="Screenshot 2024-11-07 at 23 47 54" src="https://media.github.pie.apple.com/user/163538/files/fa4f7b98-21b7-49de-a0bf-d99a224122eb">

After:
<img width="1440" alt="Screenshot 2024-11-07 at 23 49 11" src="https://media.github.pie.apple.com/user/163538/files/ab3a5a0a-2b6c-4327-9d3e-77f3bc7a0795">

## PR Readiness Checks
- [ ] Your PR title conforms to conventional commits `<type>: <jira-ticket-num><title>`, for example: `fix: PRSDM-123 issue with login` with a maximum of 100 characters
- [ ] You have performed a self-review of your changes via the GitHub UI
- [ ] Comments were added to new code that can not explain itself (see [reference 1](https://bpoplauschi.github.io/2021/01/20/Clean-Code-Comments-by-Uncle-Bob-part-2.html) and [reference 2](https://blog.cleancoder.com/uncle-bob/2017/02/23/NecessaryComments.html))
- [ ] New code adheres to the following quality standards:
  - Function Length ([see reference](https://martinfowler.com/bliki/FunctionLength.html))
  - Meaningful Names ([see reference](https://learning.oreilly.com/library/view/clean-code-a/9780136083238/chapter02.xhtml))
  - DRY ([see reference](https://java-design-patterns.com/principles/#keep-things-dry))
  - YAGNI ([see reference](https://java-design-patterns.com/principles/#yagni))
- [ ] Changes were tested locally

2024-11-08 07:31 UTC, CharlRitterDev approved these changes

2024-11-11 08:15 UTC, Zalaras requested changes

2024-11-11 08:15 UTC, Zalaras commented on layouts/partials/article/title.html
> +                {{ with .Parent }}
Can we rather use recursion here and just pass the depth value and then return when no more parents

2024-11-11 08:15 UTC, Zalaras commented on layouts/partials/article/title.html
> +            <h5>{{ .Title }}</h5>
I think you can do the following:
```suggestion
    {{ if lt $headingLevel 6 }}
         <h{{ $headingLevel }}>{{ .Title }}</h{{ $headingLevel }}>
    {{ else }}
         <h6>{{ .Title }}</h6>
    {{ end }}
```

2024-11-11 08:15 UTC, Zalaras commented on layouts/partials/article/title.html
> +                {{ with .Parent }}
You'll need to create a new partial

2024-11-14 07:51 UTC, julianbyte commented on layouts/partials/article/title.html
> +            <h5>{{ .Title }}</h5>
Thanks!

2024-11-14 12:59 UTC, Zalaras approved these changes
LGTM, just one comment for clean up :)

2024-11-14 12:59 UTC, Zalaras commented on layouts/partials/article/title.html
> +            <h6>{{ .Title }}</h6>
If you're capping the heading level here then you don't need the other else further down

2024-11-21 19:47 UTC, merged